services:
  php:
    build: .
    container_name: symfony_app
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
    depends_on:
      - db
    working_dir: /var/www
    command: bash -c "composer install && php -S 0.0.0.0:8000 -t public"

  db:
    image: mysql:8.0
    container_name: symfony_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
